export const COLORS = {
  navy: "#0D1B2A",
  navyCard: "#1A2E45",
  navyLight: "#243B55",
  purple: "#8B2FC9",
  purpleDark: "#6A1FA0",
  purpleLight: "#A855F7",
  text: "#E8E8F0",
  muted: "#8899AA",
  border: "#1E3A52",
  success: "#22C55E",
  warning: "#F59E0B",
  danger: "#EF4444",
  info: "#38BDF8",
};

export const S = {
  app: { display: "flex", height: "100vh", background: COLORS.navy, fontFamily: "'Inter', sans-serif", color: COLORS.text, overflow: "hidden" },
  sidebar: { width: 240, background: COLORS.navyCard, borderRight: `1px solid ${COLORS.border}`, display: "flex", flexDirection: "column" },
  sidebarLogo: { padding: "20px", borderBottom: `1px solid ${COLORS.border}`, display: "flex", alignItems: "center", gap: 10 },
  logoIcon: { width: 36, height: 36, background: COLORS.navyLight, borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 800, color: COLORS.purple },
  logoText: { fontSize: 16, fontWeight: 700, color: COLORS.text },
  navSection: { padding: "16px 20px 8px", fontSize: 10, color: COLORS.muted, letterSpacing: 1, textTransform: "uppercase" },
  navItem: (active) => ({ display: "flex", alignItems: "center", gap: 10, padding: "10px 16px", margin: "2px 12px", borderRadius: 8, cursor: "pointer", fontSize: 13.5, color: active ? COLORS.text : COLORS.muted, background: active ? COLORS.purple + "22" : "transparent", borderLeft: active ? `3px solid ${COLORS.purple}` : "3px solid transparent", transition: "all 0.15s" }),
  main: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  topbar: { height: 60, background: COLORS.navyCard, borderBottom: `1px solid ${COLORS.border}`, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 24px" },
  content: { flex: 1, overflow: "auto", padding: 24 },
  card: { background: COLORS.navyCard, border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: 20, marginBottom: 16 },
  input: { width: "100%", background: COLORS.navyLight, border: `1px solid ${COLORS.border}`, borderRadius: 8, padding: "10px 14px", color: COLORS.text, fontSize: 14, outline: "none", boxSizing: "border-box" },
  btn: (variant = "primary") => ({ padding: "10px 20px", borderRadius: 8, border: "none", cursor: "pointer", fontSize: 14, fontWeight: 600, background: variant === "primary" ? COLORS.purple : COLORS.navyLight, color: "#fff" }),
  loginPage: { minHeight: "100vh", background: COLORS.navy, display: "flex", alignItems: "center", justifyContent: "center" },
  loginCard: { background: COLORS.navyCard, border: `1px solid ${COLORS.border}`, borderRadius: 16, padding: 40, width: 380 },
  tag: (color) => ({ display: "inline-block", padding: "2px 8px", borderRadius: 4, fontSize: 11, fontWeight: 600, background: color + "22", color: color }),
};